### ISSUE TITLE
Melhorar os testes

### ISSUE THREAD

**Issue by vitorcapdeville** [vivianalobo/lnmixsurv#10]
Existem testes que verificam o bom funcionamento do modelo, mas eles precisam ser melhorados. 

O fato do resultado do modelo não ser determinístico dificulta o teste, mas eu acho que podemos ver como outros modelos bayesianos realizam os testes e melhorar os nossos testes.

**Comment by victorney** [comment]
Quanto ao ponto do modelo não ser determinístico, parece que adicionar tolerance = 10^-2 nos testes fez tudo funcionar bem e passar em diversos testes. Irei ler quanto à questão dos testes unitários logo após mudar a estrutura de campos de cubos para matrizes, assim fazemos testes mais coerentes com o que realmente está sendo aplicado no código

**Comment by vitorcapdeville** [comment]
Vamos dar uma olhada como outro pacotes bayesianos realizam os testes também

**Comment by victorney** [comment]
Dei uma atenção para esse assunto em #41, Todas funções que o usuário usa, por agora, são cobertas por testes.
