### ISSUE TITLE
Eventos no tempo 0

### ISSUE THREAD

**Issue by vitorcapdeville** [vivianalobo/lnmixsurv#11]
O modelo não permite que existam eventos no tempo zero, uma vez que usa a ligação log(y). Devemos retornar um erro informativo quando o usuário fornecer dados em que existam eventos no tempo zero.

**Comment by victorney** [comment]
Podemos passar pro usuário um argumento boolean na função que se chame _remove_zeros_. Se _remove_zeros = TRUE_, a gente pode remover os zeros no pré-processamento dos dados e informar aos usuários quantas observações foram removidas. Se _remove_zeros = FALSE_, a gente pode solicitar a especificação de um pequeno valor para somar a todos os tempos só para tomar o log do tempo sem problemas numéricos.

**Comment by vitorcapdeville** [comment]
Não acho mto bom implementarmos isso não, Victor. O objetivo do pacote é modelagem, e não tratamento de dados.
Incluir essa funcionalidade significaria que a nossa função faz duas coisas: trata os dados e ajusta os modelos. As funções devem fazer apenas uma coisa. Também acho que não seja o escopo do pacote tratar dados, mesmo que ficasse em outra função.

**Comment by victorney** [comment]
Ok, na nova branch que abri eu adicionei uma etapa de verificação para ver se há pelo menos um evento que ocorreu no tempo zero.  Se sim, o R aborta e informa ao usuário que pelo menos um evento ocorreu no tempo zero. Também adicionei um novo teste para verificar se essa feature segue funcionando

**Comment by victorney** [comment]
Implementado em #15
