### ISSUE TITLE
Refatorar predict

### ISSUE THREAD

**Issue by vitorcapdeville** [vivianalobo/lnmixsurv#2]
Precisamos refatorar as funções referentes ao predict. 
As funções foram construidas originalmente pensando em apenas 2 componentes.
Com a introdução das n componentes, o código ficou um pouco bagunçado, e relativamente lento.
Gostaria de repensar os apply's e lapply's, e se for o caso, colocar o extract_surv_haz no c++.

**Comment by victorney** [comment]
#36 

Adicionei outras funções para auxiliar na visualização de como ficou o ajuste no próprio conjunto de dados (como a plot_fit_on_data_em()) e a parte de predição de sobrevivência já está em C++ para o EM

**Comment by victorney** [comment]
Resolvido em #36.
