### ISSUE TITLE
progresso não é exibido quando cores > 1 mesmo com show_progress=TRUE

### ISSUE THREAD

**Issue by vitorcapdeville** [vivianalobo/lnmixsurv#20]
O modelo não exibe o progresso quando rodando em paralelo, mesmo que o argumento show_progress seja TRUE.

```
require(lnmixsurv)

set.seed(3000)

dados <- lnmixsurv::sim_data$data

survival_ln_mixture(
  Surv(y, delta) ~ x, 
  dados, 
  intercept = TRUE, 
  show_progress = TRUE,
  cores=2,
  chains=2
)

survival_ln_mixture(
  Surv(y, delta) ~ x, 
  dados, 
  intercept = TRUE, 
  show_progress = TRUE,
  cores=2,
  chains=1
)
```

**Comment by victorney** [comment]
[](url)Acho que a única forma de resolver essa parte vai ser abrir mão totalmente do uso da paralelização em R e jogar a paralelização dentro do código em C++. Printar de dentro de um cluster pro R no Windows não é tão fácil quanto parece, descobri que aquele parâmetro **outfile = ""** é meio que um "hack" pro Linux.

Quanto a esse problema no Windows, encontrei os seguintes links:
https://stackoverflow.com/questions/56501937/how-to-print-from-clusterapply
https://stackoverflow.com/questions/16717461/how-can-i-print-or-cat-when-using-parallel?noredirect=1&lq=1

[Essa resposta](https://stackoverflow.com/questions/62308162/why-dont-parallel-jobs-print-in-rstudio?rq=3) me pareceu promissora e eu tentei aplicar ela localmente. Apesar de funcionar e ter a saída do progresso, essa saída não é exibida enquanto o código roda. Apenas tudo junto de vez só, como se fosse lido um .txt dentro do R.

**Comment by vitorcapdeville** [comment]
Victor, olhei essas perguntas q você mostrou e na última, que você diz ser promissora, o primeiro comentário na pergunta menciona que o problema tá relacionado com o Rstudio, e eles estão certos. Se você salvar o código de exemplo em um arquivo e rodar esse arquivo usando o Rscript no power shell, o output é printado de forma adequada.

**Comment by victorney** [comment]
Show, mas de qualquer forma vou tentar a paralelização para dentro do C++ com o OpenMP. Assim, a gente resolve issue e também melhora a performance do código em geral. Por agora, o código leva uns 10 segundos para iniciar os clusters, o OpenM usa forking que não tem esse tempo inicial para gerar os clusters e também parece funcionar melhor que clusters. Vou abrir uma branch aqui e acredito fortemente que não vai mudar muita coisa se paralelizarmos dentro do C++, apenas um pós-processamento da saída no R

**Comment by victorney** [comment]
Resolvida em #22
