### ISSUE TITLE
Incluir paralelização.

### ISSUE THREAD

**Issue by vitorcapdeville** [vivianalobo/lnmixsurv#3]
Com a entrada das n componentes, o código para rodar as cadeias em paralelo foi removido. 
Precisamos descobrir como controlar o a geração de números aleatórios quando estamos rodando cadeias em paralelo.
Precisamos garantir que quando usamos set.seed(1) e rodamos 4 cadeias em paralelo ele retorna um output que se repete sempre que fixamos o set.seed(1) e rodamos 4 cadeias em paralelo com os mesmos dados e covariáveis.
O controle precisa ser feito a partir do R, ou seja, a semente deve ser setada pelo R e o Rcpp deve respeitar essa semente.
A paralelização pode ser feita dentro do R ou dentro do c++ (usando OpenMP).

https://stackoverflow.com/questions/18967763/set-rng-state-with-openmp-and-rcpp
https://www.r-bloggers.com/2020/09/future-1-19-1-making-sure-proper-random-numbers-are-produced-in-parallel-processing/

**Comment by victorney** [comment]
O que eu penso para isso é passar as seeds como argumento das cadeias e definir a seed do RNG dentro do código do C++, ou seja, a função do C++ teria um argumento que recebe uma seed. Sei que  [GNU](https://www.gnu.org/software/gsl/doc/html/rng.html) tem toda estrutura necessária para amostrar de distribuições de probabilidade que precisamos, como a Dirichlet, normal multivariada e Gamma, além de toda questão de gerador de números aleatórios. Vou testar se simplesmente definirmos a seed pelo GNU dentro do código, sem alterar os códigos para amostrar valores aleatórios, resolve essa issue.

Uma outra possibilidade é abrirmos mão das funções pré-implementadas e implementarmos nós mesmos todas funções para amostrar números aleatórios. Minha motivação para isso é que assim conseguimos controlar toda estrutura RNG do algoritmo e que construir funções para amostrar números aleatórios das distribuições que utilizamos é bem fácil. Basicamente, precisaríamos implementar uma estrutura de RNG e 3 funções para amostrar: amostrar de uma Gamma (e, por consequência, já resolvemos a Dirichlet), amostrar de uma normal multivariada e amostrar de uma distribuição univariada. Esse caminho parece ser o melhor a seguir, visto que conseguimos definir a seed como um argumento de entrada e não ficaríamos dependentes das estruturas externas para isso

**Comment by victorney** [comment]
Apesar da paralelização estar sendo feita no R, essa primeira implementação está incluída em #15
