### ISSUE TITLE
Melhorar output do algoritmo C++

### ISSUE THREAD

**Issue by vitorcapdeville** [vivianalobo/lnmixsurv#5]
Atualmente, o lognormal_mixture_gibbs retorna um field (lista) de cubes (arrays de 3 dimensões) contendo as cadeias dos parâmetros.
São 3 elementos no field:

theta, 1 x numero_componentes_mistura x numero_iteracoes
phi 1 x numero_componentes_mistura x numero_iteracoes
beta numero_covariaveis x nmero_componentes_mistura x numero_iteracoes

Além disso, o algoritmo sempre é rodado através do sequential_lognormal_gibbs (ou futuramente parallel_lognormal_gibbs) que retorna um field onde cada elemento é um field de cubes, representando as diferentes cadeias executadas.

No R, esse field de fields de cubes se converte para uma lista de lista de arrays, e fazemos algumas manipulações para colocar esses dados num formato que o posterior::as_draws_matrix entende.

Essa estrutura tá bem bagunçada, e seria interessante repensar em como exportar essas cadeias do Rcpp num formato mais conveniente.

**Comment by victorney** [comment]
Em breve irei dar uma olhada melhor nisso. Tenho um código que a saída de cada função é uma matriz, considero uma estrutura mais simples de se trabalhar. A parte chata é preencher as colunas na ordem. A ordem que eu estava utilizando era: eta_1, intercept_1, x1_1, x2_1, ..., phi_1, eta_2, intercept_2, ..., e assim por diante.

Vou verificar no código como isso é passado para a função mas espero resolver essa issue em breve, junto com rodar as cadeias em paralelo. Para fechar essa parte inicial, faltaria somente resolver a questão do RNG no C++

**Comment by victorney** [comment]
Incluído em #15
