### ISSUE TITLE
Problemas de convergência

### ISSUE THREAD

**Issue by vitorcapdeville** [vivianalobo/lnmixsurv#7]
Para alguns dados, ou até mesmo para algumas seeds diferentes no mesmo dado, alguns parâmetros do modelo estouram e o algoritmo não consegue inverter a matriz para gerar os betas.

Precisamos entender a causa disso, e verificar uma possível solução.

<inserir código aqui com o problema acontecendo - dá pra pegar dos exemplos da documentação alterando a seed>

**Comment by victorney** [comment]
O novo código implementado tem convergido satisfatoriamente para regiões que, às vezes, não são próximas dos valores reais, mas que não afetam a estimativa. A identificabilidade dos grupos nos dados utilizados é importante, visto que se duas componentes de mistura possuem valores observados bem próximos, então o algoritmo pode definir que apenas uma componente represente ambos os grupos. Apesar de não ser o esperado, a estimativa não é afetada.
